version: '3.1'

services:
  PollerBox:
    restart: always
    image: bernhardpollerspoeck/pollerbox:latest
    ports:
      - "8080:8080"
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /dev:/dev