version: '3.1'

services:
  PollerBox:
    restart: always
    image: bernhardpollerspoeck/pollerbox:latest
    ports:
      - "8080:8080"
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
    privileged: true