version: '3.1'

services:
  PollerBox:
    restart: always
    image: bernhardpollerspoeck/pollerbox:latest
    privileged: true
    ports:
      - "8080:8080"
    user: root
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - AUDIODEV=hw:1,0
      - POLLER_BOX_USE_SPI=true
      - POLLER_BOX_PLAY_STARTUP=true